{
 "title": "Node core metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "label_values(node_cpu, host)" },
   {
    "name": "netdev_group",
    "query": "label_values(node_network_receive_bytes, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{host=~\"$host\"} / count(count(node_cpu{host=~\"$host\"}) without (mode)) without (cpu)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail{host=~\"$host\",device=~\"/dev/.*\"} / node_filesystem_size{host=~\"$host\",device=~\"/dev/.*\"})",
     "legendFormat": "{{device}} on {{host}}"
    }
   ]
  },
  {
   "title": "Memory Used (percent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemAvailable{host=~\"$host\"} / node_memory_MemTotal{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Available (absolute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal{host=~\"$host\"} - node_memory_MemAvailable{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{host=~\"$host\",device=~\"($netdev_group).*\"}[1m])",
     "legendFormat": "{{host}} {{device}} received"
    },
    {
     "expr": "- irate(node_network_transmit_bytes{host=~\"$host\",device=~\"($netdev_group).*\"}[1m])",
     "legendFormat": "{{host}} {{device}} transmitted"
    }
   ]
  }
 ]
}