{
 "title": "PostgreSQL dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(postgres_backends_quantity, host)"
   },
   {
    "name": "db",
    "query": "label_values(postgres_backends_quantity{host=~\"$host\"}, db)"
   },
   {
    "name": "table",
    "query": "label_values(postgres_table_stats_n_dead_tup{host=~\"$host\", db=~\"$db\"}, relname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of backends",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postgres_backends_quantity{host=~\"$host\",db=~\"$db\",state=\"active\"}",
     "legendFormat": "Active in {{db}} on {{host}}"
    },
    {
     "expr": "postgres_backends_quantity{host=~\"$host\",db=~\"$db\",state=\"idle\"}",
     "legendFormat": "Idle in {{db}} on {{host}}"
    }
   ]
  },
  {
   "title": "Number of slow queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postgres_slowqueries_quantity{host=~\"$host\",db=~\"$db\"}",
     "legendFormat": "{{duration}}s in {{db}} on {{host}}"
    }
   ]
  },
  {
   "title": "Number of dead tuples",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postgres_table_stats_n_dead_tup{host=~\"$host\",db=~\"$db\",relname=~\"$table\"}",
     "legendFormat": "In table {{relname}} of {{db}} on {{host}}"
    }
   ]
  }
 ]
}